# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cube.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'cube.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ncube.proto\x12\x04\x63ube\"\x1f\n\rNumberRequest\x12\x0e\n\x06number\x18\x01 \x01(\x05\"\x1d\n\x0bNumberReply\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32\x42\n\x0b\x43ubeService\x12\x33\n\x07GetCube\x12\x13.cube.NumberRequest\x1a\x11.cube.NumberReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cube_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NUMBERREQUEST']._serialized_start=20
  _globals['_NUMBERREQUEST']._serialized_end=51
  _globals['_NUMBERREPLY']._serialized_start=53
  _globals['_NUMBERREPLY']._serialized_end=82
  _globals['_CUBESERVICE']._serialized_start=84
  _globals['_CUBESERVICE']._serialized_end=150
# @@protoc_insertion_point(module_scope)
