# docker-compose.yml
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
  importer:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - api
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017
    command: poetry run typer importer.run fetch

  processor:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - api
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017
    command: poetry run typer importer.run process
  exporter:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - api
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017
    command: poetry run typer exporter.run export